stages:
  - deploy

deploy:
  stage: deploy
  script:
    - whoami
    - pwd
    - ls -lah
    - sudo mv index.html /var/www/html/index.html
  tags:
    - tpt-ec1
  only:
    - master
  environment:
    name: test
    url: http://ec2-13-53-44-83.eu-north-1.compute.amazonaws.com/