stages:
  - review
  - deploy

deploy:
  stage: deploy
  script:
    - sudo mv index.html /var/www/html/index.html
  tags:
    - tpt-ec1
  only:
    - master
  environment:
    name: test
    url: http://ec2-13-53-44-83.eu-north-1.compute.amazonaws.com/

review:start:
  stage: review
  variables:
    DEPLOY_DIR: "/var/www/html/$CI_COMMIT_REF_SLUG"
  script:
    - sudo mkdir -p "$DEPLOY_DIR"
    - sudo mv index.html "$DEPLOY_DIR/index.html"
  only:
    - branches
  except:
    - master
  tags:
    - tpt-ec1
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: "http://ec2-13-53-44-83.eu-north-1.compute.amazonaws.com/$CI_COMMIT_REF_SLUG/"